config/routes.rb
Rails.application.routes.draw do
  root                'home#index'
  get 'about'     =>  'home#about'
  get 'contact'   =>  'home#contact'
  get 'faq'       =>  'home#faq'
#  post 'contact'  =>  'home#contact'

  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    mailer: "users/mailer",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    shared: "users/shared",
    unlocks: "users/unlocks"
  }
  resources :users do
    resources :groups
  end
  resources :groups do
    resources :users
  end
  resources :contributions
  resources :vote_challenges
  resources :vote_comments
  resources :comments
  resources :challenges
  resources :categories do
    resources :challenges
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :challenge
  
  has_many :vote_comments

  validates :comment,           presence: true,
                                length: { within: 20..250 }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @comment_count = Comment.count + 1
  end

  # GET /comments/1/edit
  def edit
    @comment_count = Comment.count
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        @comment_count = Comment.count + 1
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        @comment_count = Comment.count
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :challenge_id, :comment)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<form class="form-horizontal" role="form">
  <%= form_for(@comment) do |f| %>
    <% if @comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :user_id, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.number_field :user_id, class: "form-control" %>
      </div>
    </div>
    <div class="field form-group">
      <%= f.label :challenge_id, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.number_field :challenge_id, class: "form-control" %>
      </div>
    </div>
    <div class="field form-group">
      <%= f.label :comment, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_area :comment, class: "form-control" %>
      </div>
    </div>
    <div class="actions col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-default" %>
    </div>
  <% end %>
</form>

app/views/comments/edit.html.erb
<% @page_header="Editing Comment" %>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<% @page_header="Listing Comments" %>
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Challenge</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.challenge_id %></td>
        <td><%= comment.comment %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<% @page_header="New Comment" %>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<% @page_header="Comment Info" %>
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Challenge:</strong>
  <%= @comment.challenge_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>