config/routes.rb
Rails.application.routes.draw do
  root                'home#index'
  get 'about'     =>  'home#about'
  get 'contact'   =>  'home#contact'
  get 'faq'       =>  'home#faq'
#  post 'contact'  =>  'home#contact'

  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    mailer: "users/mailer",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    shared: "users/shared",
    unlocks: "users/unlocks"
  }
  resources :users do
    resources :groups
  end
  resources :groups do
    resources :users
  end
  resources :contributions
  resources :vote_challenges
  resources :vote_comments
  resources :comments
  resources :challenges
  resources :categories do
    resources :challenges
  end

end

app/models/vote_challenge.rb
class VoteChallenge < ActiveRecord::Base

  belongs_to :challenge
  belongs_to :user

end

app/controllers/vote_challenges_controller.rb
class VoteChallengesController < ApplicationController
  before_action :set_vote_challenge, only: [:show, :edit, :update, :destroy]

  # GET /vote_challenges
  # GET /vote_challenges.json
  def index
    @vote_challenges = VoteChallenge.all
  end

  # GET /vote_challenges/1
  # GET /vote_challenges/1.json
  def show
  end

  # GET /vote_challenges/new
  def new
    @vote_challenge = VoteChallenge.new
  end

  # GET /vote_challenges/1/edit
  def edit
  end

  # POST /vote_challenges
  # POST /vote_challenges.json
  def create
    @vote_challenge = VoteChallenge.new(vote_challenge_params)

    respond_to do |format|
      if @vote_challenge.save
        format.html { redirect_to @vote_challenge, notice: 'Vote challenge was successfully created.' }
        format.json { render :show, status: :created, location: @vote_challenge }
      else
        format.html { render :new }
        format.json { render json: @vote_challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vote_challenges/1
  # PATCH/PUT /vote_challenges/1.json
  def update
    respond_to do |format|
      if @vote_challenge.update(vote_challenge_params)
        format.html { redirect_to @vote_challenge, notice: 'Vote challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote_challenge }
      else
        format.html { render :edit }
        format.json { render json: @vote_challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vote_challenges/1
  # DELETE /vote_challenges/1.json
  def destroy
    @vote_challenge.destroy
    respond_to do |format|
      format.html { redirect_to vote_challenges_url, notice: 'Vote challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote_challenge
      @vote_challenge = VoteChallenge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_challenge_params
      params.require(:vote_challenge).permit(:user_id, :challenge_id)
    end
end

app/helpers/vote_challenges_helper.rb
module VoteChallengesHelper
end

app/views/vote_challenges/_form.html.erb
<%= form_for(@vote_challenge) do |f| %>
  <% if @vote_challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote_challenge.errors.count, "error") %> prohibited this vote_challenge from being saved:</h2>

      <ul>
      <% @vote_challenge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :challenge_id %><br>
    <%= f.number_field :challenge_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vote_challenges/edit.html.erb
<h1>Editing Vote Challenge</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote_challenge %> |
<%= link_to 'Back', vote_challenges_path %>

app/views/vote_challenges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vote Challenges</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Challenge</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vote_challenges.each do |vote_challenge| %>
      <tr>
        <td><%= vote_challenge.user_id %></td>
        <td><%= vote_challenge.challenge_id %></td>
        <td><%= link_to 'Show', vote_challenge %></td>
        <td><%= link_to 'Edit', edit_vote_challenge_path(vote_challenge) %></td>
        <td><%= link_to 'Destroy', vote_challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote challenge', new_vote_challenge_path %>

app/views/vote_challenges/new.html.erb
<h1>New Vote Challenge</h1>

<%= render 'form' %>

<%= link_to 'Back', vote_challenges_path %>

app/views/vote_challenges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @vote_challenge.user_id %>
</p>

<p>
  <strong>Challenge:</strong>
  <%= @vote_challenge.challenge_id %>
</p>

<%= link_to 'Edit', edit_vote_challenge_path(@vote_challenge) %> |
<%= link_to 'Back', vote_challenges_path %>